makecode:
  target: microbit
  platform: microbit
  home_url: https://makecode.microbit.org/
theme: jekyll-theme-cayman
title: Digit Display (MAX6958)
description: Makecode extension for Digit Display (MAX6958)
include:
  - assets
  - README.md
